import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { TooltipProvider } from "@radix-ui/react-tooltip";
import { Toaster } from "sonner";
import HolyLoader from "holy-loader";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { Onborda, OnbordaProvider } from "onborda";
import { tourSteps } from "@/features/tour/steps";
import TourCard from "@/features/tour/card";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <OnbordaProvider>
          <Onborda
            steps={tourSteps}
            showOnborda={true}
            interact={true}
            shadowRgb="55,48,163"
            shadowOpacity="0.8"
            cardComponent={TourCard}
          >
            <NuqsAdapter>
              <Toaster />
              <HolyLoader
                color="hsl(var(--primary))"
                height={3}
                speed={250}
                easing="linear"
                showSpinner={false}
              />
              <TooltipProvider>{children}</TooltipProvider>
            </NuqsAdapter>
          </Onborda>
        </OnbordaProvider>
      </body>
    </html>
  );
}
