import type { Metadata } from "next";
import { Lexend_Deca } from "next/font/google";
import "./globals.css";
import { TooltipProvider } from "@radix-ui/react-tooltip";
import { Toaster } from "sonner";
import HolyLoader from "holy-loader";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { Onborda, OnbordaProvider } from "onborda";
import { tourSteps } from "@/features/tour/steps";
import TourCard from "@/features/tour/card";
import QueryProvider from "@/contexts/queryProvider";

import { auth } from "@/features/auth/server";
import { getPath } from "@/lib/headers";
import { headers } from "next/headers";
import { redirect } from "next/navigation";
import React from "react";

const font = Lexend_Deca({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const head = headers();
  const data = await auth.api.getSession({
    headers: head,
  });
  const path = await getPath();
  if (!data?.session && path !== "/login") return redirect("/login");

  if (data?.session) {
    if (!data?.session.activeOrganizationId && path !== "/org")
      return redirect("/org");
  }

  return (
    <html lang="en">
      <body className={`${font.className} antialiased`}>
        <QueryProvider>
          <OnbordaProvider>
            <Onborda
              steps={tourSteps}
              showOnborda={true}
              interact={true}
              shadowRgb="55,48,163"
              shadowOpacity="0.8"
              cardComponent={TourCard}
            >
              <NuqsAdapter>
                <Toaster />
                <HolyLoader
                  color="hsl(var(--primary))"
                  height={3}
                  speed={250}
                  easing="linear"
                  showSpinner={false}
                />
                <TooltipProvider>{children}</TooltipProvider>
              </NuqsAdapter>
            </Onborda>
          </OnbordaProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
