import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { TooltipProvider } from "@radix-ui/react-tooltip";
import { Toaster } from "sonner";
import HolyLoader from "holy-loader";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import NavBar from "@/components/common/nav";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NuqsAdapter>
          <Toaster />
          <HolyLoader
            color="hsl(var(--primary))"
            height={3}
            speed={250}
            easing="linear"
            showSpinner={false}
          />
          <TooltipProvider>
            <NavBar />
            {children}
          </TooltipProvider>
        </NuqsAdapter>
      </body>
    </html>
  );
}
